development:
  adapter: mysql2
  encoding: utf8
  database: academyclass_development
  user: admin_dev
  password: Uhp9ZKFQT2
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  database: academyclass
  username: admin
  password: ppo4vkdss4vyzyjk
  host: 109.107.35.254

test:
  adapter: mysql2
  encoding: utf8
  database: academyclass_test
  user: root
  pool: 5
  timeout: 5000
