#development:
#  adapter: mysql2
#  encoding: utf8
#  database: academyclass
#  user: root
#  pool: 5
#  timeout: 5000

development:
  adapter: mysql2
  encoding: utf8
  database: academyclass
  username: admin
  password: ppo4vkdss4vyzyjk
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: academyclass_test
  user: root
  pool: 5
  timeout: 5000
