development:
  adapter: mysql2
  encoding: utf8
  database: academyclass
  username: admin
  password: j3bb5%5e6wbVv2cC2
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  database: academyclass
  username: admin
  password: ppo4vkdss4vyzyjk
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: academyclass_test
  user: root
  pool: 5
  timeout: 5000
